import { ThemeProvider } from '@/components/providers/theme-context'
import { ChildProps } from '@/types'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: ChildProps) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white transition-colors dark:bg-gray-900 dark:text-white custom-scrollbar`}
			>
				<ThemeProvider>
					<NextTopLoader
						color='#007aff'
						initialPosition={0.5}
						crawlSpeed={200}
						height={2}
						crawl={true}
						showSpinner={false}
						easing='ease'
						speed={200}
						shadow='0 0 10px #007aff,0 0 5px #007aff'
					/>
					<Toaster
						position='top-center'
						toastOptions={{
							duration: 4000,
							style: {
								background: '#1f2937',
								color: '#fff',
								borderRadius: '8px',
								padding: '12px 16px',
							},
							success: {
								iconTheme: {
									primary: '#4ade80',
									secondary: '#fff',
								},
							},
							error: {
								iconTheme: {
									primary: '#ef4444',
									secondary: '#fff',
								},
							},
						}}
					/>
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
